config/routes.rb
Rails.application.routes.draw do


  # resources :sessions
  # get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'login', to: 'sessions#new', as: 'login'
  # get 'signup', to: 'users#new', as: 'signup'

  match '/courses/update_batch' => 'courses#update_batch', via: [:get, :post]

  get '/courses/manage_course' => 'courses#manage_course'
  get '/courses/manage_batches' => 'courses#manage_batches'

  get '/students/student_register/:id' => 'students#student_register'
  get '/students/attendance_register' => 'students#attendance_register'




  # get 'users/search_users'
  get "users/view_all"

  get '/backup' => 'user#backup'
  # get 'attendances/daily_register'
  get 'attendances/report'
  get 'attendances/update_attendance'
  match 'attendances/filter', :via => [:get, :post]
  get 'attendance_list/:id' => 'attendances#attendance_list'
  get '/attendance_report' => 'attendances#attendance_report'



  get 'list_students_by_course/:id' => 'students#list_students_by_course'
  get "students/view_all"
  get 'students/search_students'

  resources :timetable_entries

  resources :attendances

  resources :attendances do
    get "delete"
  end



    resources :application, only: :index do
      member do
        get :set_language
      end
    end

    resources :assessment_scores do
      collection do
        get :exam_fa_groups
        get :observation_groups
      end
    end

    resources :attendances do
      collection do
        get :daily_register
        get :subject_wise_register
        get :list_subject
      end
    end

    resources :attendance_reports do
      collection do
        get :advance_search
        get :mode
        get :subject
        get :show_mode
        get :year
        get :report
        get :report_pdf
        get :filter
      end
    end
  # B

    resources :batches do
      collection do
        get :batches_ajax
        get :assign_tutor
        get :delete
        get :show
      end
      resources :exam_groups
      #batch.resources :additional_exam_groups
      resources :elective_groups, :as => :electives do
        post :new
      end
    end

    resources :batch_transfers, only: :index do
      collection do
        get :update_batch
        get :subject_transfer
        get :show_batch
        get :graduation
        post :graduation
        get :transfer
        patch :transfer
      end
    end
  # C

    resources :calendar, only: :index do
      collection do
        get :new_calendar
        get :show_holiday_event_tooltip
        get :event_delete
        get :show_event_tooltip
      end
    end

    resources :cce_exam_categories

    resources :cce_grade_sets do
      member do
        get :new_grade
        post :new_grade
        get :edit_grade
        post :edit_grade
        get :update_grade
        post :update_grade
        post :destroy_grade
      end
    end

    resources :cce_settings do
      collection do
        get :basic
        get :scholastic
        get :co_scholastic
      end
    end

    resources :cce_weightages, only: :index do
      member do
        get :assign_courses
        post :assign_courses
      end
      collection do
        get :assign_weightages
        post :assign_weightages
      end
    end

    resources :class_designations, only: :index do
      collection do
        get :load_class_designations
        get :create_class_designation
        post :create_class_designation
        get :edit_class_designation
        get :delete_class_designation
        get :update_class_designation
        post :update_class_designation
      end
    end

    resources :class_timings, except: :show do
      collection do
        get :show_class_timing
      end
    end

    resources :configuration, :controller=>"settings", only: :index do
      collection do
        get :settings
        post :settings
      end
    end

    # resources :configuration, :controller=>"settings", :path => "configuration"
    ##feed 'courses/manage_course', :controller => 'courses' ,:action=>'manage_course'
    ##feed 'courses/manage_batches', :controller => 'courses' ,:action=>'manage_batches'

    resources :courses do
      collection do
        get :grouped_batches
        post :grouped_batches
        get :create_batch_group
        post :create_batch_group
        get :edit_batch_group
        post :edit_batch_group
        get :update_batch_group
        post :update_batch_group
        get :delete_batch_group
        post :delete_batch_group
        get :assign_subject_amount
        post :assign_subject_amount
        get :edit_subject_amount
        post :edit_subject_amount
        get :destroy_subject_amount
        post :destroy_subject_amount
        get :manage_course
        get :manage_batches
        get :update_batch
        get :delete
      end
    end
  # D
  # E
    resources :elective_groups do
      collection do
        get :new
        get :delete
      end
    end

    resources :employee_attendance do
      collection do
        get :employee_leave_reset_by_department
        get :add_leave_types
        get :report
        get :manual_reset
        get :add_leave_types
        post :add_leave_types
        get :edit_leave_types
        post :edit_leave_types
        get :delete_leave_types
        get :update_attendance_report
        get :emp_attendance
        get :leave_history
        get :employee_attendance_pdf
        get :leave_reset_settings
        post :leave_reset_settings
        get :employee_leave_reset_all
        get :employee_leave_reset_by_employee
        get :update_leave_history
        post :update_leave_history
        get :update_employee_leave_reset_all
        get :list_department_leave_reset
        get :update_department_leave_reset
        post :update_department_leave_reset
        get :employee_view_all
        get :employee_search_ajax
        get :employee_leave_details
        get :employee_wise_leave_reset
        get :employees_list
      end
    end

    resources :employee, only: :index do
      collection do
        get :hr
        get :subject_assignment
        get :update_subjects
        get :select_department
        get :settings
        get :employee_management
        get :employee_attendance
        get :payslip
        get :search
        get :department_payslip
        get :admission1
        post :admission1
        get :advanced_search
        get :advanced_search_pdf
        get :view_all
        get :payslip_approve
        get :add_category
        post :add_category
        get :add_position
        post :add_position
        get :add_department
        post :add_department
        get :add_grade
        post :add_grade
        get :add_bank_details
        post :add_bank_details
        get :add_additional_details
        post :add_additional_details
        get :edit_category
        post :edit_category
        delete :delete_category
        get :edit_position
        post :edit_position
        delete :delete_position
        get :edit_department
        post :edit_department
        delete :delete_department
        get :edit_grade
        post :edit_grade
        delete :delete_grade
        get :edit_bank_details
        post :edit_bank_details
        get :delete_bank_details
        get :edit_additional_details
        patch :edit_additional_details
        get :delete_additional_details
        get :update_positions
        get :update_employees
        get :admission2
        post :admission2
        get :admission3
        post :admission3
        get :admission3_1
        post :admission3_1
        get :edit_privilege
        post :edit_privilege
        get :admission4
        post :admission4
        get :select_department_employee
        get :rejected_payslip
        get :update_employee_select_list
        get :create_monthly_payslip
        post :create_monthly_payslip
        get :add_payslip_category
        post :add_payslip_category
        get :create_payslip_category
        post :create_payslip_category
        get :remove_new_paylist_category
        get :update_rejected_employee_list
        get :payslip_date_select
        get :view_rejected_payslip
        get :update_rejected_payslip
        get :edit_rejected_payslip
        post :edit_rejected_payslip
        get :profile
        get :remove
        get :change_reporting_manager
        post :change_reporting_manager
        get :edit1
        post :edit1
        get :profile_pdf
        get :change_to_former
        post :change_to_former
        get :delete
        post :department_payslip
        get :view_employee_payslip
        get :employee_individual_payslip_pdf
        get :update_reporting_manager_name
        get :select_reporting_manager
        get :assign_employee
        get :remove_employee
        get :employees_list
        get :search_ajax
        get :remove_subordinate_employee
        get :one_click_payslip_generation
        post :one_click_payslip_generation
        get :payslip_revert_date_select
        get :one_click_payslip_revert
        post :one_click_payslip_revert
      end
    end

    resources :employee_attendances do
      collection do
        get :show_dept
        get :delete_attendance
      end
    end

    resources :event do
      collection do
        get :index
        post :index
        get :show
        get :select_course
        get :confirm_event
        get :cancel_event
        get :course_event
        post :course_event
        get :remove_batch
        get :select_employee_department
        get :department_event
        post :department_event
        get :remove_department
        get :edit_event
        post :edit_event
      end
    end

    resources :exam, only: :index do
      collection do
        get :settings
        get :create_exam
        get :generate_reports
        post :generate_reports
        get :report_center
        get :previous_batch_exams
        get :update_batch

app/views/attendances_old/_delete.html.erb
<div class="modal-header">
  <h3>Delete Article</h3>
</div>
<div class="modal-body">
<ul class="errors"></ul>
Are you sure you wish to delete <b><%= @attendance.name %></b>?
</div>
<div class="modal-footer">
  <%= link_to "Yes, Delete This Article", attendance_path(@attendance), method: :delete, remote: true, class: "btn btn-danger" %>
  <%= link_to "No, Please Don't", "#", class: "btn", data: { dismiss: "modal" } %>
</div>

app/views/attendances_old/_edit.html.erb
<div class="modal-header">
  <h3><%= "Editing #{@attendance.month_date}" %></h3>
</div>
<%= render "form" %>

app/views/attendances_old/_form.html.erb
<%= form_for @attendance, remote: true, html: {class: 'new_attendance_form', style: "display:inline;" } do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>

          <%= f.hidden_field :student_id %>
          <%= f.hidden_field :batch_id %>
          <%= f.hidden_field :month_date %>


    <div class="row">
       <div class="control-group col-sm-12">
         <%= f.label :reason, class:"control-label" %>
         <%= f.text_field :reason %>
       </div>
    </div>
    <br>
    <div class="row">
       <div class="control-group col-sm-12">
          <%= f.check_box(:forenoon, {checked: true}) %>
         <%= f.label :forenoon, class:"control-label" %>
       </div>
       <div class="control-group col-sm-12">
          <%= f.check_box(:afternoon, {checked: true}) %>
         <%= f.label :afternoon, class:"control-label" %>
       </div>
    </div>


  </div>
    <br>
  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
<% end %>


<script type="text/javascript">
  $(document).ready(function(){
    alert('in')
    $('.new_attendance_form').submit(function(){
      var valuesToSubmit = $(this).serialize();
      $.ajax({
        method:"POST",
        url: $(this).attr('action'),
        data: valuesToSubmit,
        dataType: "JSON", // you want a difference between normal and ajax-calls, and json is standard
        success: function(json){
        //act on result.
          id =  "#" + json.student_id + "_" + parseInt(json.month_date.split(/[- ]+/).pop());  // CREATING THE ID USING EMP_ID AND DAY
           // alert(id);
           $(id).html("<a style='text-decoration:none;text-align:center' data-remote='true' href='/attendances/new?student_id=" + json.student_id + "&amp;month_date=" + json.month_date + "'>X</a>");
          $('.modal').modal('hide');
          // $('#myqty').focus();
        },

        // Code to run if the request fails; the raw request and
        // status codes are passed to the function
        error: function( xhr, status, errorThrown ) {
          $.each(xhr.responseJSON, function(k, v) {
              //display the key and value pair
              alert(k + ' ' + v);
          });
        }
      });
      return false;
    });
  });

</script>

app/views/attendances_old/_new.html.erb
<div class="modal-header">
<h3>Leave form</h3>
</div>
<%= render "form" %>

app/views/attendances_old/_save.js.erb
$("ul.errors").html("")
<% if @attendance.errors.any? %>
  <% @attendance.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".attendance-index").html("<%= escape_javascript(render 'index') %>")
  $("#attendance-modal").modal("hide")
<% end %>

app/views/attendances_old/create.js.erb
<%= render "save" %>

app/views/attendances_old/delete.js.erb
$("#inner-attendance-modal").html("<%= escape_javascript(render 'delete') %>")
$("#attendance-modal").modal("show")

app/views/attendances_old/destroy.js.erb
<%= render "save" %>

app/views/attendances_old/edit.html.erb
<h1>Editing attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances_old/edit.js.erb
$("#inner-attendance-modal").html("<%= escape_javascript(render 'edit') %>")
$("#attendance-modal").modal("show")

app/views/attendances_old/index.html.erb
<div class="container">
   <%= link_to "New Attendance", new_attendance_path, remote: true, class: "btn btn-pink pull-right" %>
  <div class="new-attendance"></div>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <td></td>
        <td></td>
      </tr>
    </thead>
    <tbody class="attendance-index">
      <%= render "index" %>
    </tbody>
  </table>
</div>
<div id="attendance-modal" class="modal fade">
  <div class="modal-dialog">
    <div id="inner-attendance-modal" class="modal-content"></div>
  </div>
</div>

app/views/attendances_old/new.html.erb
<h1>Leave Form</h1>

<%= render 'form' %>

<%#= link_to 'Back', attendances_path %>

app/views/attendances_old/new.js.erb
$("#inner-attendance-modal").html("<%= escape_javascript(render 'new') %>")
$("#attendance-modal").modal("show")

app/views/attendances_old/update.js.erb
<%= render "save" %>