config/routes.rb
Rails.application.routes.draw do


  # resources :sessions
  # get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'login', to: 'sessions#new', as: 'login'
  # get 'signup', to: 'users#new', as: 'signup'

  match '/courses/update_batch' => 'courses#update_batch', via: [:get, :post]

  get '/courses/manage_course' => 'courses#manage_course'
  get '/courses/manage_batches' => 'courses#manage_batches'

  get '/students/student_register/:id' => 'students#student_register'
  get '/students/attendance_register' => 'students#attendance_register'




  # get 'users/search_users'
  get "users/view_all"

  get '/backup' => 'user#backup'
  # get 'attendances/daily_register'
  get 'attendances/report'
  get 'attendances/update_attendance'
  match 'attendances/filter', :via => [:get, :post]
  get 'attendance_list/:id' => 'attendances#attendance_list'
  get '/attendance_report' => 'attendances#attendance_report'



  get 'list_students_by_course/:id' => 'students#list_students_by_course'
  get "students/view_all"
  get 'students/search_students'

  resources :timetable_entries

  resources :attendances

  resources :attendances do
    get "delete"
  end



    resources :application, only: :index do
      member do
        get :set_language
      end
    end

    resources :assessment_scores do
      collection do
        get :exam_fa_groups
        get :observation_groups
      end
    end

    resources :attendances do
      collection do
        get :daily_register
        get :subject_wise_register
        get :list_subject
      end
    end

    resources :attendance_reports do
      collection do
        get :advance_search
        get :mode
        get :subject
        get :show_mode
        get :year
        get :report
        get :report_pdf
        get :filter
      end
    end
  # B

    resources :batches do
      collection do
        get :batches_ajax
        get :assign_tutor
        get :delete
        get :show
      end
      resources :exam_groups
      #batch.resources :additional_exam_groups
      resources :elective_groups, :as => :electives do
        post :new
      end
    end

    resources :batch_transfers, only: :index do
      collection do
        get :update_batch
        get :subject_transfer
        get :show_batch
        get :graduation
        post :graduation
        get :transfer
        patch :transfer
      end
    end
  # C

    resources :calendar, only: :index do
      collection do
        get :new_calendar
        get :show_holiday_event_tooltip
        get :event_delete
        get :show_event_tooltip
      end
    end

    resources :cce_exam_categories

    resources :cce_grade_sets do
      member do
        get :new_grade
        post :new_grade
        get :edit_grade
        post :edit_grade
        get :update_grade
        post :update_grade
        post :destroy_grade
      end
    end

    resources :cce_settings do
      collection do
        get :basic
        get :scholastic
        get :co_scholastic
      end
    end

    resources :cce_weightages, only: :index do
      member do
        get :assign_courses
        post :assign_courses
      end
      collection do
        get :assign_weightages
        post :assign_weightages
      end
    end

    resources :class_designations, only: :index do
      collection do
        get :load_class_designations
        get :create_class_designation
        post :create_class_designation
        get :edit_class_designation
        get :delete_class_designation
        get :update_class_designation
        post :update_class_designation
      end
    end

    resources :class_timings, except: :show do
      collection do
        get :show_class_timing
      end
    end

    resources :configuration, :controller=>"settings", only: :index do
      collection do
        get :settings
        post :settings
      end
    end

    # resources :configuration, :controller=>"settings", :path => "configuration"
    ##feed 'courses/manage_course', :controller => 'courses' ,:action=>'manage_course'
    ##feed 'courses/manage_batches', :controller => 'courses' ,:action=>'manage_batches'

    resources :courses do
      collection do
        get :grouped_batches
        post :grouped_batches
        get :create_batch_group
        post :create_batch_group
        get :edit_batch_group
        post :edit_batch_group
        get :update_batch_group
        post :update_batch_group
        get :delete_batch_group
        post :delete_batch_group
        get :assign_subject_amount
        post :assign_subject_amount
        get :edit_subject_amount
        post :edit_subject_amount
        get :destroy_subject_amount
        post :destroy_subject_amount
        get :manage_course
        get :manage_batches
        get :update_batch
        get :delete
      end
    end
  # D
  # E
    resources :elective_groups do
      collection do
        get :new
        get :delete
      end
    end

    resources :employee_attendance do
      collection do
        get :employee_leave_reset_by_department
        get :add_leave_types
        get :report
        get :manual_reset
        get :add_leave_types
        post :add_leave_types
        get :edit_leave_types
        post :edit_leave_types
        get :delete_leave_types
        get :update_attendance_report
        get :emp_attendance
        get :leave_history
        get :employee_attendance_pdf
        get :leave_reset_settings
        post :leave_reset_settings
        get :employee_leave_reset_all
        get :employee_leave_reset_by_employee
        get :update_leave_history
        post :update_leave_history
        get :update_employee_leave_reset_all
        get :list_department_leave_reset
        get :update_department_leave_reset
        post :update_department_leave_reset
        get :employee_view_all
        get :employee_search_ajax
        get :employee_leave_details
        get :employee_wise_leave_reset
        get :employees_list
      end
    end

    resources :employee, only: :index do
      collection do
        get :hr
        get :subject_assignment
        get :update_subjects
        get :select_department
        get :settings
        get :employee_management
        get :employee_attendance
        get :payslip
        get :search
        get :department_payslip
        get :admission1
        post :admission1
        get :advanced_search
        get :advanced_search_pdf
        get :view_all
        get :payslip_approve
        get :add_category
        post :add_category
        get :add_position
        post :add_position
        get :add_department
        post :add_department
        get :add_grade
        post :add_grade
        get :add_bank_details
        post :add_bank_details
        get :add_additional_details
        post :add_additional_details
        get :edit_category
        post :edit_category
        delete :delete_category
        get :edit_position
        post :edit_position
        delete :delete_position
        get :edit_department
        post :edit_department
        delete :delete_department
        get :edit_grade
        post :edit_grade
        delete :delete_grade
        get :edit_bank_details
        post :edit_bank_details
        get :delete_bank_details
        get :edit_additional_details
        patch :edit_additional_details
        get :delete_additional_details
        get :update_positions
        get :update_employees
        get :admission2
        post :admission2
        get :admission3
        post :admission3
        get :admission3_1
        post :admission3_1
        get :edit_privilege
        post :edit_privilege
        get :admission4
        post :admission4
        get :select_department_employee
        get :rejected_payslip
        get :update_employee_select_list
        get :create_monthly_payslip
        post :create_monthly_payslip
        get :add_payslip_category
        post :add_payslip_category
        get :create_payslip_category
        post :create_payslip_category
        get :remove_new_paylist_category
        get :update_rejected_employee_list
        get :payslip_date_select
        get :view_rejected_payslip
        get :update_rejected_payslip
        get :edit_rejected_payslip
        post :edit_rejected_payslip
        get :profile
        get :remove
        get :change_reporting_manager
        post :change_reporting_manager
        get :edit1
        post :edit1
        get :profile_pdf
        get :change_to_former
        post :change_to_former
        get :delete
        post :department_payslip
        get :view_employee_payslip
        get :employee_individual_payslip_pdf
        get :update_reporting_manager_name
        get :select_reporting_manager
        get :assign_employee
        get :remove_employee
        get :employees_list
        get :search_ajax
        get :remove_subordinate_employee
        get :one_click_payslip_generation
        post :one_click_payslip_generation
        get :payslip_revert_date_select
        get :one_click_payslip_revert
        post :one_click_payslip_revert
      end
    end

    resources :employee_attendances do
      collection do
        get :show_dept
        get :delete_attendance
      end
    end

    resources :event do
      collection do
        get :index
        post :index
        get :show
        get :select_course
        get :confirm_event
        get :cancel_event
        get :course_event
        post :course_event
        get :remove_batch
        get :select_employee_department
        get :department_event
        post :department_event
        get :remove_department
        get :edit_event
        post :edit_event
      end
    end

    resources :exam, only: :index do
      collection do
        get :settings
        get :create_exam
        get :generate_reports
        post :generate_reports
        get :report_center
        get :previous_batch_exams
        get :update_batch

app/controllers/exam_groups_controller.rb
class ExamGroupsController < ApplicationController

  before_filter :login_required
  filter_access_to :all
  before_filter :initial_queries
  before_filter :protect_other_student_data
  before_filter :restrict_employees_from_exam
  before_filter :protect_other_batch_exams, :only => [:show, :index]
  # in_place_edit_with_validation_for :exam_group, :name
  # in_place_edit_with_validation_for :exam, :maximum_marks
  # in_place_edit_with_validation_for :exam, :minimum_marks
  # in_place_edit_with_validation_for :exam, :weightage

  def index
    @sms_setting = SmsSetting.new
    @exam_groups = @batch.exam_groups
    if @current_user.employee?
      @user_privileges = @current_user.privileges
      @employee_subjects= @current_user.employee_record.subjects.map { |n| n.id}
      if @employee_subjects.empty? and !@user_privileges.map{|p| p.name}.include?('ExaminationControl') and !@user_privileges.map{|p| p.name}.include?('EnterResults')
        flash[:notice] = "#{t('flash_msg4')}"
        redirect_to :controller => 'user', :action => 'dashboard'
      end
    end
  end

  def new
    @user_privileges = @current_user.privileges
    @cce_exam_categories = CceExamCategory.all if @batch.cce_enabled?
    if !@current_user.admin? and !@user_privileges.map{|p| p.name}.include?('ExaminationControl') and !@user_privileges.map{|p| p.name}.include?('EnterResults')
      flash[:notice] = "#{t('flash_msg4')}"
      redirect_to :controller => 'user', :action => 'dashboard'
    end
  end

  def create
    @exam_group = ExamGroup.new(exam_group_params)
    @exam_group.batch_id = @batch.id
    @type = @exam_group.exam_type
    @error=false
    unless @type=="Grades"
      params[:exam_group][:exams_attributes].each do |exam|
        if exam[1][:_delete].to_s=="0" and @error==false
          unless exam[1][:maximum_marks].present?
            @exam_group.errors.add_to_base("#{t('maxmarks_cant_be_blank')}")
            @error=true
          end
          unless exam[1][:minimum_marks].present?
            @exam_group.errors.add_to_base("#{t('minmarks_cant_be_blank')}")
            @error=true
          end
        end
      end
    end
    if @error==false and @exam_group.save
      flash[:notice] =  "#{t('exam_groups.flash1')}"
      redirect_to batch_exam_groups_path(@batch)
    else
      @cce_exam_categories = CceExamCategory.all if @batch.cce_enabled?
      render 'new'
    end
  end

  def edit
    @exam_group = ExamGroup.find params[:id]
    @cce_exam_categories = CceExamCategory.all if @batch.cce_enabled?
  end

  def update
    @exam_group = ExamGroup.find params[:id]
    if @exam_group.update_attributes(params[:exam_group])
      flash[:notice] = "#{t('flash2')}"
      redirect_to [@batch, @exam_group]
    else
      @cce_exam_categories = CceExamCategory.all if @batch.cce_enabled?
      render 'edit'
    end
  end

  def delete
    @exam_group = ExamGroup.where(:id => params[:id]).includes(:exams).first
    if @current_user.employee?
      @employee_subjects= @current_user.employee_record.subjects.map { |n| n.id}
      if @employee_subjects.empty? and !@current_user.privileges.map{|p| p.name}.include?("ExaminationControl") and !@current_user.privileges.map{|p| p.name}.include?("EnterResults")
        flash[:notice] = "#{t('flash_msg4')}"
        redirect_to :controller => 'user', :action => 'dashboard'
      end
    end
    flash[:notice] = "#{t('exam_groups.flash3')}" if @exam_group.destroy
        redirect_to :action => 'index', :batch_id => @batch.id
  end

  def show
    @exam_group = ExamGroup.where(:id => params[:id]).includes(:exams).first
    if @current_user.employee?
      @user_privileges = @current_user.privileges
      @employee_subjects= @current_user.employee_record.subjects.map { |n| n.id}
      if @employee_subjects.empty? and !@current_user.privileges.map{|p| p.name}.include?("ExaminationControl") and !@current_user.privileges.map{|p| p.name}.include?("EnterResults")
        flash[:notice] = "#{t('flash_msg4')}"
        redirect_to :controller => 'user', :action => 'dashboard'
      end
    end
  end

  private
  def initial_queries
    @batch = Batch.where(:id => params[:batch_id]).includes(:course).first unless params[:batch_id].nil?
    @course = @batch.course unless @batch.nil?
  end

  def protect_other_batch_exams
    @user_privileges = @current_user.privileges
    if !@current_user.admin? and !@user_privileges.map{|p| p.name}.include?('ExaminationControl') and !@user_privileges.map{|p| p.name}.include?('EnterResults')
      @user_subjects = @current_user.employee_record.subjects.all(:group => 'batch_id')
      @user_batches = @user_subjects.map{|x|x.batch_id} unless @current_user.employee_record.blank? or @user_subjects.nil?

      unless @user_batches.include?(params[:batch_id].to_i)
        flash[:notice] = "#{t('flash_msg4')}"
        redirect_to :controller => 'user', :action => 'dashboard'
      end
    end
  end
  
  def exam_group_params
    params.require(:exam_group).permit(:start_date, :end_date, :subject_id, :name, :exam_type, :exams_attributes => [:id, :subject_id, :start_time, :end_time, :maximum_marks, :minimum_marks, :grading_level_id, :weightage, :event_id]) if params[:exam_group]
  end
end

app/views/exam_groups/edit.html.haml
- # Fedena
- #Copyright 2010 Foradian Technologies Private Limited
- #
- #This product includes software developed at
- #Project Fedena - http://www.projectfedena.org/
- #
- #Licensed under the Apache License, Version 2.0 (the "License");
- #you may not use this file except in compliance with the License.
- #You may obtain a copy of the License at
- #
- #  http://www.apache.org/licenses/LICENSE-2.0
- #
- #Unless required by applicable law or agreed to in writing,
- #software distributed under the License is distributed on an
- #"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
- #KIND, either express or implied.  See the License for the
- #specific language governing permissions and limitations
- #under the License.
#content-header
  = image_tag("examination/show_exam.png")
  %h1= t('exams_text')
  %h3= t('edit_exam_group')
  #app-back-button
    = back_button
#page-yield
  - unless flash[:notice].nil?
    %p.flash-msg
      = flash[:notice]
  .box
    .bread_crumb
      = link_to t('course_text'), courses_path
      »
      \#{link_to @course.full_name, @course} »
      \#{link_to "#{t('batch')}  #{@batch.name}"} »
      \#{link_to "#{t('exam_text')}", batch_exam_groups_path(@batch)} »
      \#{t('edit_exam')}
    = form_for [@batch, @exam_group] do |f|
      = f.error_messages
      .label-field-pair
        %label{:for => "exam_name"}= f.label "#{t('new_text')}"
        .text-input-bg
          = f.text_field :name
      #sub_button= submit_tag "", :value => "► #{t('save')}", :class => "submit_button"

app/views/exam_groups/index.html.erb
<%#= javascript_include_tag :application %>
<%#= stylesheet_link_tag("exam_groups/index.css") %>
<div id="content-header">
  <%#= image_tag("examination/show_exam.png") %>
  <h1>
    <%= t('exams_text') %>
  </h1>
  <h3>
    <%= t('exam_groups_text') %>
  </h3>
  <div id="app-back-button">
    <%#= back_button %>
  </div>
</div>
<!-- <div class="inner-tab-menu"> -->
<div class="bread_crumb">
    <% if @current_user.admin? or @user_privileges.map{|p| p.name}.include?('ExaminationControl') or @user_privileges.map{|p| p.name}.include?('EnterResults') %>
      <% if permitted_to? :new,:exam_groups %>
          <%= link_to "#{t('new_text')}", new_batch_exam_group_path(@batch), class: "label label-lg label-pink arrowed-right" %>  »
      <% end %>
    <% end %>
    <% if permitted_to? :grouping,:exam %>
        <%= link_to "#{t('connect_exams')}", {:controller=>'exam', :action=>'grouping', :id=>@batch}, class: "label label-lg arrowed-in label-pink arrowed-right" %>
    <% end %>
</div><br>
<div id="page-yield">
  <% unless flash[:notice].nil? %>
    <p class="flash-msg">
      <%= flash[:notice] %>
    </p>
  <% end %>
  <div class="bread_crumb">
    <%= link_to t('exams_text'), :controller => "exam", :action=>"index" %> » 
    <%= link_to "#{t('exam_management')}", :controller => "exam", :action => "create_exam" %> » 
    <%= t('exam_groups_text') %>
  </div>
  <div class="box">
    <table id="listing" width="100%" class="table table-striped">
      <tr class="tr-head">
        <td>
          <%= t('exam_name') %>
        </td>
        <% if @current_user.admin? or @user_privileges.map{|p| p.name}.include?('ExaminationControl') or @user_privileges.map{|p| p.name}.include?('EnterResults') %>
          <td>
            <%= t('actions') %>
            <%= image_tag("loader.gif", :align => "absmiddle", :border => 0, :id => "loader", :style =>"display: none;" ) %>
          </td>
        <% end %>
      </tr>
      <% @config = Setting.available_modules %>
      <% @exam_groups.each do |exam_group| %>
        <tr class="tr-<%= cycle('odd', 'even') %>">
          <td class="col-2">
            <%= link_to exam_group.name, [@batch, exam_group] %>
            <% if @current_user.admin? or @user_privileges.map{|p| p.name}.include?('ExaminationControl') or @user_privileges.map{|p| p.name}.include?('EnterResults') %>
              <span>
                <small>
                  <%= link_to("#{t('delete_text')}", {:action=> :delete, :id => exam_group.id, :batch_id=> @batch.id}, method: :DELETE, class: "btn btn-danger btn-sm btn-warning btn-bold") if exam_group.removable? %>
                  <s>
                    <%= "#{t('delete_text')}" unless exam_group.removable? %>
                  </s>
                </small>
              </span>
            <% end %>
          </td>
          <% if @current_user.admin? or @user_privileges.map{|p| p.name}.include?('ExaminationControl') or @user_privileges.map{|p| p.name}.include?('EnterResults') %>
            <td class="col-2">
              <small>
                <% unless exam_group.is_published %>
                  <%= link_to("#{t('publish_exam_schedule')}",{:controller=>'exam',:action=>'publish',:id=>exam_group.id,:status=>"schedule"}, :remote=> true) %>
                <% else %>
                  <% unless  exam_group.result_published %>
                    <%= t('schedule_published') %>
                    <% if @sms_setting.application_sms_active and @sms_setting.exam_result_schedule_sms_active %>
                      <%= link_to "#{t('resend')}",{:controller=>'exam',:action=>'publish',:id=>exam_group.id,:status=>"schedule"}, :remote => true %>
                      <%= t('sms_notification') %>
                      <br/>
                    <% end %>
                    <%= link_to t('publish_exam_result'), { controller: :exam, action: :publish, id: exam_group.id, status: :result}, method: :DELETE, :remote => true, :confirm=>"#{t('delete_confirm_msg')}" %>
                  <% else %>
                    <%= t('result_published') %>
                    <% if @sms_setting.application_sms_active and @sms_setting.exam_result_schedule_sms_active %>
                      <%= link_to "#{t('resend_sms_notification')}",{:controller=>'exam',:action=>'publish',:id=>exam_group.id,:status=>"result"}, :remote => true %>
                    <% end %>
                  <% end %>
                <% end %>
                <span id="publish-notice-<%= exam_group.id %>"></span>
              </small>
            </td>
          <% end %>
        </tr>
      <% end %>
      <% if @batch.cce_enabled? %>
        <% if permitted_to? :observation_groups,  :assessment_scores %>
          <tr class="tr-<%= cycle('odd', 'even') %>">
            <td class="col-1" colspan="2">
              <%= link_to "Co-Scholastic result entry", observation_groups_assessment_scores_path(:batch_id=>@batch.id) %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>
    <div class="extender"></div>
  </div>
</div>

app/views/exam_groups/show.html.erb
<div id="content-header">
  <%#= image_tag("examination/show_exam.png") %>
  <h1>
    <%= t('exams_text') %>
  </h1>
  <h3>
    <%= t('view_exam_groups') %>
  </h3>
  <div id="app-back-button">
    <%#= back_button %>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <% if permitted_to? :publish,:exam %>
      <% if @exam_group.is_published %>
        <li>
          <%= link_to t('publish_exam_result'), url_for(controller: :exam, action: :publish, id: @exam_group.id, status: :result), remote: true %>
        </li>
      <% end %>
    <% end %>
    <% if permitted_to? :new,:exams %>
      <li>
        <%= link_to t('new_text'), new_exam_group_exam_path(@exam_group) %>
      </li>
    <% end %>
  </ul>
</div>
<div id="page-yield">
  <% unless flash[:notice].nil? %>
    <p class="flash-msg">
      <%= flash[:notice] %>
    </p>
  <% end %>
  <div class="bread_crumb">
    <%= link_to t('exams_text'), :controller => "exam", :action=>"index" %>
    <%= link_to "#{t('exam_management')}", :controller => "exam", :action => "create_exam" %>
    <%= link_to "#{t('exam_groups_text')}", batch_exam_groups_path(@batch) %>
    <%= @exam_group.name %>
  </div>
  <div class="box">
    <div class="update_msg">
      <% if permitted_to? :edit, :exams %>
        <h4>
          <div id="<haml_loud">
            "exam_group_name_<%= @exam_group.id %>_edit"&gt;
            <%#= in_place_editor_field :exam_group, :name, {}, {:cols => 1} %>
            <%= text_field :exam_group, :name %>
          </div>
        </h4>
      <% else %>
        <h4>
          <span>
            <%= @exam_group.name %>
          </span>
        </h4>
      <% end %>
      <h4>
        <span class="flash_color" id="publish-notice-<%= @exam_group.id %>">
          <%= image_tag("loader.gif",:align => "absmiddle", :border => 0, :id => "loader",:style =>"display: none;" )  %>
        </span>
      </h4>
    </div>
    <% @employee_subjects=[] %>
    <% @employee_subjects= @current_user.employee_record.subjects.map { |n| n.id} if @current_user.employee? %>
    <% privilege = Privilege.find_by_name("EnterResults") %>
    <% unless @exam_group.exam_type == 'Grades' %>
      <table id="listing">
        <tr class="tr-head">
          <td>
            <%= t('subject') %>
          </td>
          <td>
            <%= t('max_mark') %>
          </td>
          <td>
            <%= t('min_mark') %>
          </td>
          <% if permitted_to? :edit, :exams %>
            <td>
              <%= t('manage') %>
            </td>
          <% end %>
        </tr>
        <% @exam_group.exams.each do |exam| %>
          <% @exam = exam %>
          <% if @employee_subjects.include?(exam.subject.id) or @current_user.admin? or @user_privileges.map{|p| p.name}.include?('ExaminationControl') or @user_privileges.map{|p| p.name}.include?('EnterResults') %>
            <tr class="tr-<%= cycle('odd', 'even') %>">
              <% @exam = exam %>
              <td class="col-2">
                <%= link_to exam.subject.name, [@exam_group, exam] %>
              </td>
              <% if permitted_to? :edit, :exams %>
                <td class="col-1">
                  <div id="<haml_loud">
                    "exam_maximum_marks_<%= @exam.id %>_edit" &gt;
                    <%#= in_place_editor_field :exam, :maximum_marks,{},{:cols=>1} %>
                    <%= text_field :exam, :maximum_marks%>
                  </div>
                </td>
                <td class="col-1">
                  <div id="<haml_loud">
                    "exam_minimum_marks_<%= @exam.id %>_edit" &gt;
                    <%#= in_place_editor_field :exam, :minimum_marks,{},{:cols=>1} %>
                    <%= text_field :exam, :minimum_marks %>
                  </div>
                </td>
                <td class="col-1">
                  <% if @exam_group.result_published %>
                    <small>
                      <s>
                        <%= t('edit_text') %>
                      </s>
                    </small>
                  <% else %>
                    <small>
                      <%= link_to t('edit_text'), edit_exam_group_exam_path(@exam_group, exam) %>
                    </small>
                  <% end %>
                  <% if @exam.removable? %>
                    <small>
                      <%= link_to t('delete_text'), [@exam_group, exam], :method => 'delete', :confirm => t('delete_confirm_msg') %>
                    </small>
                  <% else %>
                    <small>
                      <s>
                        <%= t('delete_text') %>
                      </s>
                    </small>
                  <% end %>
                </td>
              <% else %>
                <td class="col-1">
                  <span>
                    <%= exam.maximum_marks %>
                  </span>
                </td>
                <td class="col-1">
                  <span>
                    <%= exam.minimum_marks %>
                  </span>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </table>
    <% else %>
      <table id="listing" width="100%">
        <tr class="tr-head">
          <td>
            <%= t('subject') %>
          </td>
          <% if permitted_to? :edit, :exams %>
            <td>
              <%= t('manage') %>
            </td>
          <% end %>
        </tr>
        <% @exam_group.exams.each do |exam| %>
          <% if @employee_subjects.include?("#{exam.subject.id}") or @current_user.admin?  or @current_user.privileges.map{|p| p.name}.include?("ExaminationControl") or @current_user.privileges.map{|p| p.name}.include?("EnterResults") %>
            <tr class="tr-<%= cycle('odd', 'even') %>">
              <% @exam = exam %>
              <td class="col-3">
                <%= link_to exam.subject.name, [@exam_group, exam] %>
              </td>
              <% if permitted_to? :edit, :exams %>
                <td class="col-1">
                  <small>
                    <%= link_to t('edit_text'), edit_exam_group_exam_path(@exam_group, exam) %>
                  </small>
                  <% if @exam.removable? %>
                    <small>
                      <%= link_to t('delete_text'), [@exam_group, exam], :method => 'delete', :confirm => t('delete_confirm_msg') %>
                    </small>
                  <% else %>
                    <small>
                      <s>
                        <%= t('delete_text') %>
                      </s>
                    </small>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </table>
    <% end %>
    <div class="extender"></div>
  </div>
</div>