config/routes.rb
Rails.application.routes.draw do


  # resources :sessions
  # get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'login', to: 'sessions#new', as: 'login'
  # get 'signup', to: 'users#new', as: 'signup'

  match '/courses/update_batch' => 'courses#update_batch', via: [:get, :post]

  get '/courses/manage_course' => 'courses#manage_course'
  get '/courses/manage_batches' => 'courses#manage_batches'

  get '/students/student_register/:id' => 'students#student_register'
  get '/students/attendance_register' => 'students#attendance_register'




  # get 'users/search_users'
  get "users/view_all"

  get '/backup' => 'user#backup'
  # get 'attendances/daily_register'
  get 'attendances/report'
  get 'attendances/update_attendance'
  match 'attendances/filter', :via => [:get, :post]
  get 'attendance_list/:id' => 'attendances#attendance_list'
  get '/attendance_report' => 'attendances#attendance_report'



  get 'list_students_by_course/:id' => 'students#list_students_by_course'
  get "students/view_all"
  get 'students/search_students'

  resources :timetable_entries

  resources :attendances

  resources :attendances do
    get "delete"
  end



    resources :application, only: :index do
      member do
        get :set_language
      end
    end

    resources :assessment_scores do
      collection do
        get :exam_fa_groups
        get :observation_groups
      end
    end

    resources :attendances do
      collection do
        get :daily_register
        get :subject_wise_register
        get :list_subject
      end
    end

    resources :attendance_reports do
      collection do
        get :advance_search
        get :mode
        get :subject
        get :show_mode
        get :year
        get :report
        get :report_pdf
        get :filter
      end
    end
  # B

    resources :batches do
      collection do
        get :batches_ajax
        get :assign_tutor
        get :delete
        get :show
      end
      resources :exam_groups
      #batch.resources :additional_exam_groups
      resources :elective_groups, :as => :electives do
        post :new
      end
    end

    resources :batch_transfers, only: :index do
      collection do
        get :update_batch
        get :subject_transfer
        get :show_batch
        get :graduation
        post :graduation
        get :transfer
        patch :transfer
      end
    end
  # C

    resources :calendar, only: :index do
      collection do
        get :new_calendar
        get :show_holiday_event_tooltip
        get :event_delete
        get :show_event_tooltip
      end
    end

    resources :cce_exam_categories

    resources :cce_grade_sets do
      member do
        get :new_grade
        post :new_grade
        get :edit_grade
        post :edit_grade
        get :update_grade
        post :update_grade
        post :destroy_grade
      end
    end

    resources :cce_settings do
      collection do
        get :basic
        get :scholastic
        get :co_scholastic
      end
    end

    resources :cce_weightages, only: :index do
      member do
        get :assign_courses
        post :assign_courses
      end
      collection do
        get :assign_weightages
        post :assign_weightages
      end
    end

    resources :class_designations, only: :index do
      collection do
        get :load_class_designations
        get :create_class_designation
        post :create_class_designation
        get :edit_class_designation
        get :delete_class_designation
        get :update_class_designation
        post :update_class_designation
      end
    end

    resources :class_timings, except: :show do
      collection do
        get :show_class_timing
      end
    end

    resources :configuration, :controller=>"settings", only: :index do
      collection do
        get :settings
        post :settings
      end
    end

    # resources :configuration, :controller=>"settings", :path => "configuration"
    ##feed 'courses/manage_course', :controller => 'courses' ,:action=>'manage_course'
    ##feed 'courses/manage_batches', :controller => 'courses' ,:action=>'manage_batches'

    resources :courses do
      collection do
        get :grouped_batches
        post :grouped_batches
        get :create_batch_group
        post :create_batch_group
        get :edit_batch_group
        post :edit_batch_group
        get :update_batch_group
        post :update_batch_group
        get :delete_batch_group
        post :delete_batch_group
        get :assign_subject_amount
        post :assign_subject_amount
        get :edit_subject_amount
        post :edit_subject_amount
        get :destroy_subject_amount
        post :destroy_subject_amount
        get :manage_course
        get :manage_batches
        get :update_batch
        get :delete
      end
    end
  # D
  # E
    resources :elective_groups do
      collection do
        get :new
        get :delete
      end
    end

    resources :employee_attendance do
      collection do
        get :employee_leave_reset_by_department
        get :add_leave_types
        get :report
        get :manual_reset
        get :add_leave_types
        post :add_leave_types
        get :edit_leave_types
        post :edit_leave_types
        get :delete_leave_types
        get :update_attendance_report
        get :emp_attendance
        get :leave_history
        get :employee_attendance_pdf
        get :leave_reset_settings
        post :leave_reset_settings
        get :employee_leave_reset_all
        get :employee_leave_reset_by_employee
        get :update_leave_history
        post :update_leave_history
        get :update_employee_leave_reset_all
        get :list_department_leave_reset
        get :update_department_leave_reset
        post :update_department_leave_reset
        get :employee_view_all
        get :employee_search_ajax
        get :employee_leave_details
        get :employee_wise_leave_reset
        get :employees_list
      end
    end

    resources :employee, only: :index do
      collection do
        get :hr
        get :subject_assignment
        get :update_subjects
        get :select_department
        get :settings
        get :employee_management
        get :employee_attendance
        get :payslip
        get :search
        get :department_payslip
        get :admission1
        post :admission1
        get :advanced_search
        get :advanced_search_pdf
        get :view_all
        get :payslip_approve
        get :add_category
        post :add_category
        get :add_position
        post :add_position
        get :add_department
        post :add_department
        get :add_grade
        post :add_grade
        get :add_bank_details
        post :add_bank_details
        get :add_additional_details
        post :add_additional_details
        get :edit_category
        post :edit_category
        delete :delete_category
        get :edit_position
        post :edit_position
        delete :delete_position
        get :edit_department
        post :edit_department
        delete :delete_department
        get :edit_grade
        post :edit_grade
        delete :delete_grade
        get :edit_bank_details
        post :edit_bank_details
        get :delete_bank_details
        get :edit_additional_details
        patch :edit_additional_details
        get :delete_additional_details
        get :update_positions
        get :update_employees
        get :admission2
        post :admission2
        get :admission3
        post :admission3
        get :admission3_1
        post :admission3_1
        get :edit_privilege
        post :edit_privilege
        get :admission4
        post :admission4
        get :select_department_employee
        get :rejected_payslip
        get :update_employee_select_list
        get :create_monthly_payslip
        post :create_monthly_payslip
        get :add_payslip_category
        post :add_payslip_category
        get :create_payslip_category
        post :create_payslip_category
        get :remove_new_paylist_category
        get :update_rejected_employee_list
        get :payslip_date_select
        get :view_rejected_payslip
        get :update_rejected_payslip
        get :edit_rejected_payslip
        post :edit_rejected_payslip
        get :profile
        get :remove
        get :change_reporting_manager
        post :change_reporting_manager
        get :edit1
        post :edit1
        get :profile_pdf
        get :change_to_former
        post :change_to_former
        get :delete
        post :department_payslip
        get :view_employee_payslip
        get :employee_individual_payslip_pdf
        get :update_reporting_manager_name
        get :select_reporting_manager
        get :assign_employee
        get :remove_employee
        get :employees_list
        get :search_ajax
        get :remove_subordinate_employee
        get :one_click_payslip_generation
        post :one_click_payslip_generation
        get :payslip_revert_date_select
        get :one_click_payslip_revert
        post :one_click_payslip_revert
      end
    end

    resources :employee_attendances do
      collection do
        get :show_dept
        get :delete_attendance
      end
    end

    resources :event do
      collection do
        get :index
        post :index
        get :show
        get :select_course
        get :confirm_event
        get :cancel_event
        get :course_event
        post :course_event
        get :remove_batch
        get :select_employee_department
        get :department_event
        post :department_event
        get :remove_department
        get :edit_event
        post :edit_event
      end
    end

    resources :exam, only: :index do
      collection do
        get :settings
        get :create_exam
        get :generate_reports
        post :generate_reports
        get :report_center
        get :previous_batch_exams
        get :update_batch

app/views/layouts-aasif/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts-aasif/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts-aasif/_navigation.html.erb
    <div id="navbar" class="navbar navbar-default">
      <script type="text/javascript">
        try{ace.settings.check('navbar' , 'fixed')}catch(e){}
      </script>

      <div class="navbar-container" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
          <span class="sr-only">Toggle sidebar</span>

          <span class="icon-bar"></span>

          <span class="icon-bar"></span>

          <span class="icon-bar"></span>
        </button>

        <div class="navbar-header pull-left">
          <a href="#" class="navbar-brand">
            <small>
              <i class="fa fa-leaf"></i>
              Ace Admin
            </small>
          </a>
        </div>

        <div class="navbar-buttons navbar-header pull-right" role="navigation">
          <ul class="nav ace-nav">
<!--             <li class="green">
              <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <i class ="ace-icon fa fa-user"></i>

                  Admin
              </a>
            </li> -->
            <% if @current_user %>
            <li class="light-blue">
              <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <i class ="ace-icon fa fa-user"></i>

                  <%#= @current_user.name %>



                <i class="ace-icon fa fa-caret-down"></i>
              </a>

              <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">

                <li>
                  <a href="<%#= user_path(current_user) %>">
                    <i class="ace-icon fa fa-user"></i>
                    Profile
                  </a>
                </li>

                <li class="divider"></li>

                <li>
                  <%#= link_to '<i class="ace-icon fa fa-power-off"></i> Logout'.html_safe, destroy_user_session_path, :method=>'delete' %>
                </li>
              </ul>
            </li>
            <% end %>
          </ul>
        </div>
      </div><!-- /.navbar-container -->
    </div>

app/views/layouts-aasif/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts-aasif/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Pundit" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Pundit" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <style type="text/css">
.ui-datepicker td a  {
  padding: 0px;
}
.ui-datepicker td {
  padding: 0px;
}

.ui-menu .ui-menu-item a:hover {
  color: #fff;
}
    </style>
  </head>
    <body class="no-skin">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">



    <div class="main-container" id="main-container">
      <script type="text/javascript">
        try{ace.settings.check('main-container' , 'fixed')}catch(e){}
      </script>

      <div id="sidebar" class="sidebar responsive">
        <script type="text/javascript">
          try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
        </script>

        <div class="sidebar-shortcuts" id="sidebar-shortcuts">
          <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
            <button class="btn btn-success">
              <i class="ace-icon fa fa-signal"></i>
            </button>

            <button class="btn btn-info">
              <i class="ace-icon fa fa-pencil"></i>
            </button>

            <button class="btn btn-warning">
              <i class="ace-icon fa fa-users"></i>
            </button>

            <button class="btn btn-danger">
              <i class="ace-icon fa fa-cogs"></i>
            </button>
          </div>

          <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
          </div>
        </div><!-- /.sidebar-shortcuts -->

        <ul class="nav nav-list">
          <li class="active">
            <a href="index-2.html">
              <i class="menu-icon fa fa-tachometer"></i>
              <span class="menu-text"> Dashboard </span>
            </a>

            <b class="arrow"></b>
          </li>

          <li class="">
            <a href="#" class="dropdown-toggle">
              <i class="menu-icon fa fa-file-o"></i>

              <span class="menu-text">
                Other Pages

                <span class="badge badge-primary">5</span>
              </span>

              <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
              <li class="">
                <a href="faq.html">
                  <i class="menu-icon fa fa-caret-right"></i>
                  FAQ
                </a>

                <b class="arrow"></b>
              </li>

              <li class="">
                <a href="error-404.html">
                  <i class="menu-icon fa fa-caret-right"></i>
                  Error 404
                </a>

                <b class="arrow"></b>
              </li>


            </ul>
          </li>

        </ul><!-- /.nav-list -->

        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
          <i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>

        <script type="text/javascript">
          try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
        </script>
      </div>

      <div class="main-content">
        <div class="main-content-inner">
          <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
              try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
            </script>

            <ul class="breadcrumb">
              <li>
                <i class="ace-icon fa fa-home home-icon"></i>
                <a href="#">Home</a>
              </li>
              <li class="active">Dashboard</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
              <form class="form-search">
                <span class="input-icon">
                  <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                  <i class="ace-icon fa fa-search nav-search-icon"></i>
                </span>
              </form>
            </div><!-- /.nav-search -->
          </div>

          <div class="page-content">


            <!-- <div class="page-header">
              <h1>
                Dashboard
                <small>
                  <i class="ace-icon fa fa-angle-double-right"></i>
                  overview &amp; stats
                </small>
              </h1>
            </div> --><!-- /.page-header -->

            <div class="row">
              <div class="col-xs-12">
                <!-- PAGE CONTENT BEGINS -->


                <div class="row">




                 <%= render 'layouts/messages' %>

                <%= yield %>














                </div><!-- /.row -->

                <!-- PAGE CONTENT ENDS -->
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.page-content -->
        </div>
      </div><!-- /.main-content -->

      <div class="footer">
        <div class="footer-inner">
          <div class="footer-content">
            <span class="bigger-120">
              <span class="blue bolder">Ace</span>
              Application &copy; 2013-2014
            </span>

            &nbsp; &nbsp;
            <span class="action-buttons">
              <a href="#">
                <i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
              </a>

              <a href="#">
                <i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
              </a>

              <a href="#">
                <i class="ace-icon fa fa-rss-square orange bigger-150"></i>
              </a>
            </span>
          </div>
        </div>
      </div>

      <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
        <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
      </a>
    </div><!-- /.main-container -->


    </main>
  </body>


</html>

app/views/layouts-aasif/attendance.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>ETrendz POS Developed by ETrendz IT Solutions</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield :head %>
<%= csrf_meta_tag %>

	</head>

	<body>

		<div class="navbar navbar-default" id="navbar">

			<div class="navbar-container" id="navbar-container">
				<div class="navbar-header pull-left">
					<a href="/" class="navbar-brand">
						<small id="fontfashion">
							<i class="icon-user"></i>
						</small>
					</a><!-- /.brand -->
				</div><!-- /.navbar-header -->

				<div class="navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">


						<li class="light-blue">
							<a data-toggle="dropdown" href="#" class="dropdown-toggle">
								<!-- <img class="nav-user-photo" src="/assets/avatars/user.png" alt="Users's Photo" /> -->
              <i class="ace-icon fa fa-user"></i>
							<small>Hi! </small>

								<i class="icon-caret-down"></i>
							</a>

							<ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">


								<li class="divider"></li>

								<li>
									<a href="/logout">
										<i class="icon-off"></i>
										Logout
									</a>
								</li>
							</ul>
						</li>
					</ul><!-- /.ace-nav -->
				</div><!-- /.navbar-header -->
			</div><!-- /.container -->
		</div>

		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<div class="main-container-inner">
				<a class="menu-toggler" id="menu-toggler" href="#">
					<span class="menu-text"></span>
				</a>

				<div class="sidebar" id="sidebar">
					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
					</script>

					<div class="sidebar-shortcuts" id="sidebar-shortcuts">
						<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
							<a href="/suppliers/new" class="btn btn-success" title='New Supplier'>
								<i class="icon-user"></i>
							</a>

							<a href="/customers/new"  class="btn btn-info" title='New Customer'>
								<i class="icon-group"></i>
							</a>
							<a href="/purchases/new" target="_blank" class="btn btn-warning" title='New Purchase'>
								<i class="icon-briefcase"></i>
				</a>

							<a href="/sales/new" target="_blank" class="btn btn-danger">
							<span class="badge badge-transparent tooltip-danger" title="2&nbsp;Important&nbsp;Events" data-rel="tooltip" data-original-title="New Sale">
										<i class="icon-gift"></i>
									</span>

				</a>
						</div>

						<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
						<span class="btn btn-success"></span>

							<span class="btn btn-info"></span>

							<span class="btn btn-warning"></span>

							<span class="btn btn-danger"></span>
						</div>
					</div><!-- #sidebar-shortcuts -->

					<ul class="nav nav-list">
					</ul><!-- /.nav-list -->

					<!-- <img class="img-responsive" src="/assets/store_logo.png"> -->

					<div class="sidebar-collapse" id="sidebar-collapse">
						<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
					</div>

					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
					</script>
				</div>

				<div class="main-content">
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="icon-home home-icon"></i>
								<a href="/">Home</a>
							</li>
							<li class="active"><%= params[:action] %></li>
						</ul><!-- .breadcrumb -->

						<div class="nav-search" id="nav-search">
							<form name="clockForm">
							<input style='padding:0px 0px; px 0px margin-top:-5px;border-radius:8px;font-size:110%;' type="button" class='btn btn-primary' name="clockButton" value="ETrendz"/>
							</form>
						</div><!-- #nav-search -->
					</div>


					<div class="page-content">
						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<% flash.each do |key, value| %>
									<div class="<%= flash_class(key) %>">
											<button type="button" class="close" data-dismiss="alert">
												<i class="icon-remove"></i>
											</button>
										  <%= value %>
									</div>
								<% end %>
									<%= yield %>
								<!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
				</div><!-- /.main-content -->

			</div><!-- /.main-container-inner -->

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="icon-double-angle-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->

	</body>

</html>

app/views/layouts-aasif/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
<style>
#fontfashion {
  font-family: 'Asia';
  url('/assets/asia.ttf') format('truetype'),
  font-weight: bold;
  font-size: 130%;
  font-style: normal;
}
</style>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "School App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "School App" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield :head %>
<%= csrf_meta_tag %>

	</head>

	<body>
		<div class="navbar navbar-default" id="navbar">

			<div class="navbar-container" id="navbar-container">
				<div class="navbar-header pull-left">
					<a href="/" class="navbar-brand">
						<small id="fontfashion">
							<i class="ace-icon fa fa-user"></i>
							<%#= Setting.get_config_value('STORE_NAME') %>
						</small>
					</a><!-- /.brand -->
				</div><!-- /.navbar-header -->

				<div class="navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">


						<li class="light-blue">
							<a data-toggle="dropdown" href="#" class="dropdown-toggle">
								<!-- <img class="nav-user-photo" src="/assets/avatars/user.png" alt="Users's Photo" /> -->
								<i class="ace-icon fa fa-user"></i>
									 Hi!
									<%#= current_user.name if current_user%>

								<i class="ace-icon fa fa-caret-down"></i>
							</a>

							<ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
								<!--
								<li>
									<a href="#">
										<i class="ace-icon fa fa-cog"></i>
										Settings
									</a>
								</li>

								<li>
									<a href="#">
										<i class="ace-icon fa fa-user"></i>
										Profile
									</a>
								</li>-->

								<li class="divider"></li>

								<li>
									<a href="/logout">
										<i class="ace-icon fa fa-off"></i>
										Logout
									</a>
								</li>
							</ul>
						</li>
					</ul><!-- /.ace-nav -->
				</div><!-- /.navbar-header -->
			</div><!-- /.container -->
		</div>

		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<div class="main-container-inner">
				<a class="menu-toggler" id="menu-toggler" href="#">
					<span class="menu-text"></span>
				</a>

				<div class="sidebar" id="sidebar">
					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
					</script>

					<div class="sidebar-shortcuts" id="sidebar-shortcuts">
						<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
							<a href="/suppliers/new" class="btn btn-success" title='New Supplier'>
								<i class="ace-icon fa fa-user"></i>
							</a>

							<a href="/customers/new"  class="btn btn-info" title='New Customer'>
								<i class="ace-icon fa fa-group"></i>
							</a>
							<a href="/purchases/new" target="_blank" class="btn btn-warning" title='New Purchase'>
								<i class="ace-icon fa fa-briefcase"></i>
				</a>

							<a href="/sales/new" target="_blank" class="btn btn-danger">
							<span class="badge badge-transparent tooltip-danger" title="2&nbsp;Important&nbsp;Events" data-rel="tooltip" data-original-title="New Sale">
										<i class="ace-icon fa fa-gift"></i>
									</span>

				</a>
						</div>

						<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
						<span class="btn btn-success"></span>

							<span class="btn btn-info"></span>

							<span class="btn btn-warning"></span>

							<span class="btn btn-danger"></span>
						</div>
					</div><!-- #sidebar-shortcuts -->

					<ul class="nav nav-list">
					</ul><!-- /.nav-list -->

					<!-- <img class="img-responsive" src="/assets/store_logo.png"> -->

					<div class="sidebar-collapse" id="sidebar-collapse">
						<i class="ace-icon fa fa-double-angle-left" data-icon1="ace-icon fa fa-double-angle-left" data-icon2="ace-icon fa fa-double-angle-right"></i>
					</div>

					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
					</script>
				</div>

				<div class="main-content">
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
							<li>
								<i class="ace-icon fa fa-home home-icon"></i>
								<a href="/">Home</a>
							</li>
							<li class="active"><%= params[:action] %></li>
						</ul><!-- .breadcrumb -->

						<div class="nav-search" id="nav-search">
							<form name="clockForm">
							<input style='padding:0px 0px; px 0px margin-top:-5px;border-radius:8px;font-size:110%;' type="button" class='btn btn-primary' name="clockButton" value="ETrendz"/>
							</form>
						</div><!-- #nav-search -->
					</div>


					<div class="page-content">
						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<% unless ((params[:controller] == 'sales') && (params[:action] == 'new')) %>
								<% flash.each do |key, value| %>
									<div class="<%= flash_class(key) %>">
											<button type="button" class="close" data-dismiss="alert">
												<i class="ace-icon fa fa-remove"></i>
											</button>
										  <%= value %>
									</div>
								<% end %>
								<% end %>
									<%= yield %>
								<!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content -->
				</div><!-- /.main-content -->

			</div><!-- /.main-container-inner -->

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="ace-icon fa fa-double-angle-up ace-icon fa fa-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->
		<input type="hidden" id="refreshed" value="no">
               <script type="text/javascript">
               onload=function(){
               var e=document.getElementById("refreshed");
               if(e.value=="no")e.value="yes";
               else{e.value="no";location.reload();}
               }
			   </script>
	</body>

</html>