config/routes.rb
Rails.application.routes.draw do


  # resources :sessions
  # get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'login', to: 'sessions#new', as: 'login'
  # get 'signup', to: 'users#new', as: 'signup'

  match '/courses/update_batch' => 'courses#update_batch', via: [:get, :post]

  get '/courses/manage_course' => 'courses#manage_course'
  get '/courses/manage_batches' => 'courses#manage_batches'

  get '/students/student_register/:id' => 'students#student_register'
  get '/students/attendance_register' => 'students#attendance_register'




  # get 'users/search_users'
  get "users/view_all"

  get '/backup' => 'user#backup'
  # get 'attendances/daily_register'
  get 'attendances/report'
  get 'attendances/update_attendance'
  match 'attendances/filter', :via => [:get, :post]
  get 'attendance_list/:id' => 'attendances#attendance_list'
  get '/attendance_report' => 'attendances#attendance_report'



  get 'list_students_by_course/:id' => 'students#list_students_by_course'
  get "students/view_all"
  get 'students/search_students'

  resources :timetable_entries

  resources :attendances

  resources :attendances do
    get "delete"
  end



    resources :application, only: :index do
      member do
        get :set_language
      end
    end

    resources :assessment_scores do
      collection do
        get :exam_fa_groups
        get :observation_groups
      end
    end

    resources :attendances do
      collection do
        get :daily_register
        get :subject_wise_register
        get :list_subject
      end
    end

    resources :attendance_reports do
      collection do
        get :advance_search
        get :mode
        get :subject
        get :show_mode
        get :year
        get :report
        get :report_pdf
        get :filter
      end
    end
  # B

    resources :batches do
      collection do
        get :batches_ajax
        get :assign_tutor
        get :delete
        get :show
      end
      resources :exam_groups
      #batch.resources :additional_exam_groups
      resources :elective_groups, :as => :electives do
        post :new
      end
    end

    resources :batch_transfers, only: :index do
      collection do
        get :update_batch
        get :subject_transfer
        get :show_batch
        get :graduation
        post :graduation
        get :transfer
        patch :transfer
      end
    end
  # C

    resources :calendar, only: :index do
      collection do
        get :new_calendar
        get :show_holiday_event_tooltip
        get :event_delete
        get :show_event_tooltip
      end
    end

    resources :cce_exam_categories

    resources :cce_grade_sets do
      member do
        get :new_grade
        post :new_grade
        get :edit_grade
        post :edit_grade
        get :update_grade
        post :update_grade
        post :destroy_grade
      end
    end

    resources :cce_settings do
      collection do
        get :basic
        get :scholastic
        get :co_scholastic
      end
    end

    resources :cce_weightages, only: :index do
      member do
        get :assign_courses
        post :assign_courses
      end
      collection do
        get :assign_weightages
        post :assign_weightages
      end
    end

    resources :class_designations, only: :index do
      collection do
        get :load_class_designations
        get :create_class_designation
        post :create_class_designation
        get :edit_class_designation
        get :delete_class_designation
        get :update_class_designation
        post :update_class_designation
      end
    end

    resources :class_timings, except: :show do
      collection do
        get :show_class_timing
      end
    end

    resources :configuration, :controller=>"settings", only: :index do
      collection do
        get :settings
        post :settings
      end
    end

    # resources :configuration, :controller=>"settings", :path => "configuration"
    ##feed 'courses/manage_course', :controller => 'courses' ,:action=>'manage_course'
    ##feed 'courses/manage_batches', :controller => 'courses' ,:action=>'manage_batches'

    resources :courses do
      collection do
        get :grouped_batches
        post :grouped_batches
        get :create_batch_group
        post :create_batch_group
        get :edit_batch_group
        post :edit_batch_group
        get :update_batch_group
        post :update_batch_group
        get :delete_batch_group
        post :delete_batch_group
        get :assign_subject_amount
        post :assign_subject_amount
        get :edit_subject_amount
        post :edit_subject_amount
        get :destroy_subject_amount
        post :destroy_subject_amount
        get :manage_course
        get :manage_batches
        get :update_batch
        get :delete
      end
    end
  # D
  # E
    resources :elective_groups do
      collection do
        get :new
        get :delete
      end
    end

    resources :employee_attendance do
      collection do
        get :employee_leave_reset_by_department
        get :add_leave_types
        get :report
        get :manual_reset
        get :add_leave_types
        post :add_leave_types
        get :edit_leave_types
        post :edit_leave_types
        get :delete_leave_types
        get :update_attendance_report
        get :emp_attendance
        get :leave_history
        get :employee_attendance_pdf
        get :leave_reset_settings
        post :leave_reset_settings
        get :employee_leave_reset_all
        get :employee_leave_reset_by_employee
        get :update_leave_history
        post :update_leave_history
        get :update_employee_leave_reset_all
        get :list_department_leave_reset
        get :update_department_leave_reset
        post :update_department_leave_reset
        get :employee_view_all
        get :employee_search_ajax
        get :employee_leave_details
        get :employee_wise_leave_reset
        get :employees_list
      end
    end

    resources :employee, only: :index do
      collection do
        get :hr
        get :subject_assignment
        get :update_subjects
        get :select_department
        get :settings
        get :employee_management
        get :employee_attendance
        get :payslip
        get :search
        get :department_payslip
        get :admission1
        post :admission1
        get :advanced_search
        get :advanced_search_pdf
        get :view_all
        get :payslip_approve
        get :add_category
        post :add_category
        get :add_position
        post :add_position
        get :add_department
        post :add_department
        get :add_grade
        post :add_grade
        get :add_bank_details
        post :add_bank_details
        get :add_additional_details
        post :add_additional_details
        get :edit_category
        post :edit_category
        delete :delete_category
        get :edit_position
        post :edit_position
        delete :delete_position
        get :edit_department
        post :edit_department
        delete :delete_department
        get :edit_grade
        post :edit_grade
        delete :delete_grade
        get :edit_bank_details
        post :edit_bank_details
        get :delete_bank_details
        get :edit_additional_details
        patch :edit_additional_details
        get :delete_additional_details
        get :update_positions
        get :update_employees
        get :admission2
        post :admission2
        get :admission3
        post :admission3
        get :admission3_1
        post :admission3_1
        get :edit_privilege
        post :edit_privilege
        get :admission4
        post :admission4
        get :select_department_employee
        get :rejected_payslip
        get :update_employee_select_list
        get :create_monthly_payslip
        post :create_monthly_payslip
        get :add_payslip_category
        post :add_payslip_category
        get :create_payslip_category
        post :create_payslip_category
        get :remove_new_paylist_category
        get :update_rejected_employee_list
        get :payslip_date_select
        get :view_rejected_payslip
        get :update_rejected_payslip
        get :edit_rejected_payslip
        post :edit_rejected_payslip
        get :profile
        get :remove
        get :change_reporting_manager
        post :change_reporting_manager
        get :edit1
        post :edit1
        get :profile_pdf
        get :change_to_former
        post :change_to_former
        get :delete
        post :department_payslip
        get :view_employee_payslip
        get :employee_individual_payslip_pdf
        get :update_reporting_manager_name
        get :select_reporting_manager
        get :assign_employee
        get :remove_employee
        get :employees_list
        get :search_ajax
        get :remove_subordinate_employee
        get :one_click_payslip_generation
        post :one_click_payslip_generation
        get :payslip_revert_date_select
        get :one_click_payslip_revert
        post :one_click_payslip_revert
      end
    end

    resources :employee_attendances do
      collection do
        get :show_dept
        get :delete_attendance
      end
    end

    resources :event do
      collection do
        get :index
        post :index
        get :show
        get :select_course
        get :confirm_event
        get :cancel_event
        get :course_event
        post :course_event
        get :remove_batch
        get :select_employee_department
        get :department_event
        post :department_event
        get :remove_department
        get :edit_event
        post :edit_event
      end
    end

    resources :exam, only: :index do
      collection do
        get :settings
        get :create_exam
        get :generate_reports
        post :generate_reports
        get :report_center
        get :previous_batch_exams
        get :update_batch

app/models/elective_group.rb
# == Schema Information
#
# Table name: elective_groups
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  batch_id   :integer
#  is_deleted :boolean          default(FALSE)
#  created_at :datetime
#  updated_at :datetime
#

#Fedena
#Copyright 2011 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

class ElectiveGroup < ActiveRecord::Base
  belongs_to :batch
  has_many :subjects

  validates_presence_of :name,:batch_id

  scope :for_batch, ->(b) { where(batch_id: b, is_deleted: false) }

  def inactivate
    update_attribute(:is_deleted, true)
  end
end

app/controllers/elective_groups_controller.rb
#Fedena
#Copyright 2011 Foradian Technologies Private Limited
#
#This product includes software developed at
#Project Fedena - http://www.projectfedena.org/
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

class ElectiveGroupsController < ApplicationController
  before_filter :pre_load_objects
  before_filter :login_required
  filter_access_to :all
  def index
    @elective_groups = ElectiveGroup.for_batch(@batch.id).includes(:subjects)
  end

  def new
    @elective_group = @batch.elective_groups.build
  end

  def create
    @elective_group = ElectiveGroup.new(elective_group_params)
    @elective_group.batch_id = @batch.id
    if @elective_group.save
      flash[:notice] = "#{t('elective_groups.flash1')}"
      redirect_to :action => :index, :batch_id => @batch.id 
    else
      render :action=>'new'
    end
  end

  def edit
    @elective_group = ElectiveGroup.find(params[:id])
  end

  def update
    @elective_group = ElectiveGroup.find(params[:id])
    if @elective_group.update_attributes(elective_group_params)
      flash[:notice] = "#{t('elective_groups.flash3')}"
      redirect_to :action => :index, :batch_id => @batch.id 
    else
      render 'edit'
    end
  end

  def delete
    @elective_group = ElectiveGroup.find(params[:id]).inactivate
    flash[:notice] =  "#{t('elective_groups.flash2')}"
    redirect_to :action => :index, :batch_id => @batch.id 
  end

  def show
    @electives = Subject.where("batch_id = ? and elective_group_id = ? and is_deleted = ? ", @batch.id,@elective_group.id, false)
  end

  private
  def pre_load_objects
    @batch = Batch.where(:id => params[:batch_id]).includes(:course).first
    @course = @batch.course
    @elective_group = ElectiveGroup.find(params[:id]) unless params[:id].nil?
  end
  
  def elective_group_params
    params.require(:elective_group).permit(:name, :batch_id, :is_deleted) if params[:elective_group]
  end
end

app/views/elective_groups/edit.html.erb
<%= stylesheet_link_tag("elective_groups/index.css") %>
<div id="content-header">
  <%= image_tag("examination/show_exam.png") %>
  <h1>
    <%= t('batches_text') %>
  </h1>
  <h3>
    <%= "#{t('new_elective')}" %>
  </h3>
  <div id="app-back-button">
    <%= back_button %>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li>
      <%= link_to t('new_text'), {:action => :new, :batch_id => @batch.id} %>
    </li>
  </ul>
</div>
<div id="page-yield">
  <% unless flash[:notice].nil? %>
    <p class="flash-msg">
      <%= flash[:notice] %>
    </p>
  <% end %>
  <div class="bread_crumb">
    <%= link_to t('course_text'), courses_path %> »
    <%= link_to @course.full_name, @course %> »
    <%= link_to "#{t('batch')} #{@batch.name}", {:controller => :batches, :action => :show , :course_id => @course.id, :id => @batch.id} %> »
    <%= link_to "#{t('electives')}", {:action => :index, :batch_id => @batch.id} %> »
    <%= t('edit_text') %>
  </div>
  <div class="box">
    <%= form_for(@elective_group, :url=> {:action => :update, :batch_id => @batch.id}) do |f| %>
      <% @elective_group.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
      <div class="label-field-pair">
        <div class="label-container">
          <%= f.label "#{t('name')}" %>
        </div>
        <div class="input-container">
          <%= f.text_field :name %>
        </div>
      </div>
      <%= submit_tag "", :value => " #{t('save')}", :class => "submit_button" %>
    <% end %>
    <div class="extender"></div>
  </div>
</div>

app/views/elective_groups/index.html.erb
<div id="content-header">
  <%= image_tag("examination/show_exam.png") %>
  <h1>
    <%= t('batches_text') %>
  </h1>
  <h3>
    <%= "#{t('new_elective')}" %>
  </h3>
  <div id="app-back-button">
    <%= back_button %>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li>
      <%= link_to t('new_text'), {:action => :new, :batch_id => @batch.id} %>
    </li>
  </ul>
</div>
<div id="page-yield">
  <% unless flash[:notice].nil? %>
    <p class="flash-msg">
      <%= flash[:notice] %>
    </p>
  <% end %>
  <div class="bread_crumb">
    <%= link_to t('course_text'), courses_path %> »
    <%= link_to @course.full_name, @course %> »
    <%= link_to "#{t('batch')} #{@batch.name}", {:controller => :batches, :action => :show , :course_id => @course.id, :id => @batch.id} %> »
    <%= link_to "#{t('electives')}", {:action => :index, :batch_id => @batch.id} %> »
    <%= t('elective_group') %>
  </div>
  <div class="box">
    <div class="bread_crumb"></div>
    <ul id="category-list">
      <% @elective_groups.each do |elective| %>
        <li class="list<%= cycle('odd', 'even') %>">
          <div class="category-name">
            <%= link_to elective.name, {:controller => :elective_groups, :action => :show , :id => elective.id} %>
          </div>
          <div class="category-edit">
            <%= link_to t('edit_text'), :controller=>"elective_groups",:action => "edit", :id =>elective.id %>
          </div>
          <% @subjects= Subject.where("elective_group_id = ? and is_deleted = ? ", elective, false) %>
          <% if @subjects.empty? %>
            <div class="category-delete">
              <%= link_to t('delete_text'), { :action => :delete , :batch_id => @batch.id, :id => elective}, method: :DELETE %>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="extender"></div>
  </div>
</div>

app/views/elective_groups/new.html.erb
<%= stylesheet_link_tag("elective_groups/new.css") %>
<div id="content-header">
  <%= image_tag("examination/show_exam.png") %>
  <h1>
    <%= t('batches_text') %>
  </h1>
  <h3>
    <%= "#{t('new_elective')}" %>
  </h3>
  <div id="app-back-button">
    <%= back_button %>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li>
      <%= link_to t('new_text'), {:action => :new, :batch_id => @batch.id} %>
    </li>
  </ul>
</div>
<div id="page-yield">
  <% unless flash[:notice].nil? %>
    <p class="flash-msg">
      <%= flash[:notice] %>
    </p>
  <% end %>
  <div class="bread_crumb">
    <%= link_to t('course_text'), courses_path %> »
    <%= link_to @course.full_name, @course %> »
    <%= link_to "#{t('batch')} #{@batch.name}", {:controller => :batches, :action => :show , :course_id => @course.id, :id => @batch.id} %> »
    <%= link_to "#{t('electives')}", {:action => :index, :batch_id => @batch.id} %> »
    <%= t('new_text') %>
  </div>
  <div class="box">
    <%= form_for(@elective_group, :url => {:action => :create, :batch_id=> @batch.id}) do |f| %>
      <% @elective_group.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
      <div class="label-field-pair">
        <div class="label-container">
          <%= f.label "#{t('name')}" %>
        </div>
        <div class="input-container">
          <%= f.text_field :name %>
        </div>
      </div>
      <br>
      <%= submit_tag "", :value => " #{t('save')}", :class => "btn btn-pink btn-sm" %>
    <% end %>
    <div class="extender"></div>
  </div>
</div>

app/views/elective_groups/show.html.erb
<div id="content-header">
  <%= image_tag("examination/show_exam.png") %>
  <h1>
    <%= t('batches_text') %>
  </h1>
  <h3>
    <%= "#{t('show_elective')}" %>
  </h3>
  <div id="app-back-button">
    <%= back_button %>
  </div>
</div>
<div id="inner-tab-menu">
  <ul>
    <li>
      <%= link_to  t('add'), { :controller=>"subjects",:action => 'new', :id => @batch,:id2=>@elective_group}, :remote => true %>
    </li>
  </ul>
</div>
<div id="page-yield">
  <div id="flash-box">
    <% unless flash[:notice].nil? %>
      <p class="flash-msg">
        <%= flash[:notice] %>
      </p>
    <% end %>
  </div>
  <div class="bread_crumb">
    
    <%= link_to t('course_text'), courses_path %> »
    <%= link_to @course.full_name, @course %> »
    <%= link_to "#{t('batch')} #{@batch.name}", {:controller => :batches, :action => :show , :course_id => @course.id, :id => @batch.id} %> »
    <%= link_to "#{t('electives')}", {:action => :index, :batch_id => @batch.id} %> »
    <%= @elective_group.name %>
  </div>
  <div class="box">
    <div id="subjects">
      <ul id="category-list">
        <% @electives.each do |subject| %>
          <li class="list<%= cycle('even','odd') %>" id="subject-<%= subject.id %>">
            <div class="category-name">
              <%= subject.name %>
            </div>
            <div class="category-code">
              <%= subject.code %>
            </div>
            <div class="category-edit">
              <%= link_to_remote("#{t('edit_text')} ", :url => { :controller=>"subjects",:action => 'edit', :id =>subject,:id2=>@elective_group}, :method => 'get' )  %>
            </div>
            <div class="category-delete">
              <%= link_to t('delete_text'), subject_path(subject), method: :DELETE, confirm: t('delete_confirm_msg') %>
            </div>
            <div class="category-assign">
              <%= link_to " #{t('assign_student')}", :controller=>"students", :action=>"electives",:id=>@batch,:id2=>subject.id %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div id="modal-box" style="display:none;"></div>
    <div class="extender"></div>
  </div>
</div>